### PR TITLE
Use different counter var to save two bytes

### PR DESCRIPTION
**Pull request by pvdz**
Well. Maybe. Perhaps the repetition packer screws that up.

### CODE REVIEW

**Comment by pvdz** [comment]
I'm going to leave it at this. Would love to golf more at it but... well, other priorities calling me :) Just cherry pick what's relevant.

**Comment by homecoded** [comment]
Nice ... will check your changes out! Thanks a lot!

**Comment by homecoded** [comment]
At some point your changes broke the demo. I just get a static screen with a hum. I am investigating.

**Comment by homecoded** [comment]
Ok, variables `s` and `t` are global counters that must not be reset every frame. If you do, you get that static hum.

**Comment by homecoded** [comment]
After all, even after putting the s and t back into the variable assignments at the top, the demo shrunk 10 bytes in size. So I merged your changes and added my fix on top.

Again, thanks a million for your contribution!

**Comment by pvdz** [comment]
At some point I'll find the time to create a fuzzer to do this kind of stuff. Some day, Gadget!

**Pull request merged**
