### PR TITLE
900 bytes version with smoother gradient

### PR DESCRIPTION
**Pull request by p01**
Shuffled the display of the clouds to save some font settings used for the text
Draw the gradient using the bgColor of the page and subpixel horizontal lines
Combined drawing of the water front and Melee island

### CODE REVIEW

**Comment by homecoded** [comment]
Thanks a lot! Is it just me or does the music sound way to high-pitched and off?

**Comment by homecoded** [comment]
Problem: The music is way off. This is because the second track is transposed down 9 halftones. So, if we use both tracks, they don't work together anymore. I am looking into that and try to find a slim solution.

Don't worry about the conflicts. I'll take care of them.

**Comment by p01** [comment]
The pitch bug is because `s` is basically `t*6.25`, so we shouldn't use `55*s` but `8.8*s`.

[edit] Glad you caught the reason of the off-ness [/edit]

Sorry about the mess up :\

**Comment by homecoded** [comment]
No worries. The two tracks are transposed differently. That's the reason for the off-ness. I already fixed that by adding 9 halftones by multiplying (1-1&d) to the 9 in the equation. But now the whole landscape shakes. The tip with the `t*6.25`may do the trick though :)

**Pull request merged**
